version: "3.9"
services:
  web:
    build: .
    command: uvicorn main:app --port 8448 --host 0.0.0.0
    volumes:
      - .:/Example
    ports:
      - 8448:8448
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: "DB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  postgres_data: